version: '3.8'
services:
  app:
    container_name: minerva-finance-app
    restart: always
    build: .
    ports:
      - "80:5000"
    environment:
      - DATABASE_URI=postgresql://minerva:athena@postgresDB:5432/minervaDB
    depends_on:
      - postgresDB
  postgresDB:
    container_name: postgresDB
    build: ./database
    environment:
      POSTGRES_USER: minerva
      POSTGRES_PASSWORD: athena
      POSTGRES_DB: minervaDB
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
