"""empty message

Revision ID: 8f0cd670fcee
Revises: da43283e1754
Create Date: 2020-10-26 20:46:23.713675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f0cd670fcee"
down_revision = "da43283e1754"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_source_polls",
        sa.Column("data_source_code", sa.String(length=50), nullable=True),
    )
    op.add_column("data_source_polls", sa.Column("foid", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "data_source_polls", "financial_objects", ["foid"], ["foid"]
    )
    op.drop_column("data_source_polls", "ticker")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_source_polls",
        sa.Column("ticker", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "data_source_polls", type_="foreignkey")
    op.drop_column("data_source_polls", "foid")
    op.drop_column("data_source_polls", "data_source_code")
    # ### end Alembic commands ###
