"""empty message

Revision ID: da43283e1754
Revises: bf664e83d7b5
Create Date: 2020-10-25 17:19:23.216393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da43283e1754'
down_revision = 'bf664e83d7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('hierarchy_rank', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('data_source_polls',
    sa.Column('ds_poll_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('ds_poll_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_source_polls')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
