export const BLANK_WINDOW = "BLANK_WINDOW";
export const SET_ACTIVE_FINANCIAL_OBJECT_ID = "SET_ACTIVE_FINANCIAL_OBJECT_ID";
export const GET_ACTIVE_FINANCIAL_OBJECT_ID = "GET_ACTIVE_FINANCIAL_OBJECT_ID";

export const FIN_OBJS_REQUESTED = "FIN_OBJS_REQUESTED";
export const FIN_OBJS_LOADED = "FIN_OBJS_LOADED";

export const STATISTICS_REQUESTED = "STATISTICS_REQUESTED";
export const STATISTICS_LOADED = "STATISTICS_LOADED";

export const RETURN_PLOT_REQUESTED = "RETURN_PLOT_REQUESTED";
export const RETURN_PLOT_LOADED = "RETURN_PLOT_LOADED";

export const API_ERRORED = "API_ERRORED";
