export const BLANK_WINDOW = "BLANK_WINDOW";
export const SET_ACTIVE_FINANCIAL_OBJECT = "SET_ACTIVE_FINANCIAL_OBJECT";
export const SET_ACTIVE_BENCHMARK_DEFAULT_FINANCIAL_OBJECT =
  "SET_ACTIVE_BENCHMARK_DEFAULT_FINANCIAL_OBJECT";

export const FIN_OBJS_REQUESTED = "FIN_OBJS_REQUESTED";
export const FIN_OBJS_LOADED = "FIN_OBJS_LOADED";

export const STATISTICS_REQUESTED = "STATISTICS_REQUESTED";
export const STATISTICS_LOADED = "STATISTICS_LOADED";

export const BENCHMARK_DEFAULT_STATISTICS_REQUESTED =
  "BENCHMARK_DEFAULT_STATISTICS_REQUESTED";
export const BENCHMARK_DEFAULT_STATISTICS_LOADED =
  "BENCHMARK_DEFAULT_STATISTICS_LOADED";

export const DATA_SOURCES_REQUESTED = "DATA_SOURCES_REQUESTED";
export const DATA_SOURCES_LOADED = "DATA_SOURCES_LOADED";

export const DATA_SOURCE_POLLS_REQUESTED = "DATA_SOURCE_POLLS_REQUESTED";
export const DATA_SOURCE_POLLS_LOADED = "DATA_SOURCE_POLLS_LOADED";

export const RETURN_PLOT_REQUESTED = "RETURN_PLOT_REQUESTED";
export const RETURN_PLOT_LOADED = "RETURN_PLOT_LOADED";

export const API_ERRORED = "API_ERRORED";
